const $=s=>document.querySelector(s);const labels={passed:'Passed',failed:'Failed',blocked:'Blocked',running:'Running',no_harness:'No harness',not_run:'Not run',not_configured:'Not configured',not_applicable:'—'};
let data,selected='',comparison='',manualCompare=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Date(s).toLocaleString();
function sum(run,layer){const r={passed:0,failed:0,skipped:0,total:0};for(const s of run?.services||[])for(const [l,x]of Object.entries(s.layers))if(!layer||l===layer)for(const k of Object.keys(r))r[k]+=x.tests?.[k]||0;return r}
function badge(x,id,layer){return `<button class="badge" data-status="${esc(x.status)}" data-service="${esc(id)}" data-layer="${layer}">${labels[x.status]||esc(x.status)}</button>`}
function percent(c,key){const v=c?.[key];return v?.percent==null?'—':`${v.percent}%<div class="bar"><span style="width:${Math.max(0,Math.min(100,v.percent))}%"></span></div><small>${v.covered} / ${v.total} ${key==='line'?'lines':'branches'}</small>`}
function render(){
 const runs=data.runs;const run=runs.find(r=>r.id===selected)||runs[0];if(!run){$('#notice').textContent='No results yet. Run the inventory or collector to begin.';return}
 const base=runs.find(r=>r.id===comparison);const counts=sum(run);const layers=run.services.flatMap(s=>Object.values(s.layers));const measured=run.services.filter(s=>s.layers.unit.coverage?.line?.percent!=null).length;
 $('#provenance').innerHTML=`${esc(run.branch)} · <strong>${esc(run.commit.slice(0,8))}</strong>${run.dirty?' · working tree changes':''}<br>${date(run.startedAt)}${run.finishedAt?'':' · in progress'}`;
 const stale=run.sourceFingerprint!==data.currentFingerprint;
 $('#notice').textContent=run.sourceChangedDuringRun?'Source changed during this run. Re-run before comparing.':stale?'Historical evidence: the current checkout differs from this run. Re-run to measure current code.':!run.finishedAt?'Collection in progress. Results update as each suite completes.':base?'Comparing saved evidence. Coverage deltas appear only for matching file scopes.':'No baseline selected. Freeze a completed run to establish your before state.';
 const metric=(label,n,sub)=>`<div class="metric"><div class="label">${label}</div><div class="number">${n}</div><div class="sub">${sub}</div></div>`;
 $('#metrics').innerHTML=metric('TESTS PASSING',counts.passed,`${counts.total} reported · ${counts.failed} failed · ${counts.skipped} skipped`)+metric('MEASURED SERVICES',measured+'/7','Unit line coverage available')+metric('MISSING UNIT HARNESSES',layers.filter(x=>x.status==='no_harness').length,'Explicit gaps, not passing checks')+metric('FAILED / BLOCKED SUITES',layers.filter(x=>['failed','blocked'].includes(x.status)).length,'Inspect logs for the reason');
 $('#services').innerHTML=run.services.map(s=>{const c=s.layers.unit.coverage;const b=base?.services.find(x=>x.id===s.id)?.layers.unit.coverage;let delta='—';
 if(c?.line?.percent!=null&&b?.line?.percent!=null){delta=c.format===b.format&&c.scopeHash===b.scopeHash?`${(c.line.percent-b.line.percent)>=0?'+':''}${(c.line.percent-b.line.percent).toFixed(1)} pp`:'Scope changed'}else if(c?.line?.percent!=null&&base)delta='New measurement';
 return `<tr><td><strong>${esc(s.id==='journeys'?'Application journeys':s.id)}</strong><small>${esc(s.language)} · ${esc(s.name)}</small></td>${['unit','integration','e2e'].map(l=>`<td>${badge(s.layers[l],s.id,l)}</td>`).join('')}<td>${percent(c,'line')}</td><td>${percent(c,'branch')}</td><td class="delta">${delta}</td></tr>`}).join('');
 $('#layers').innerHTML=['unit','integration','e2e'].map(l=>{const n=sum(run,l);const b=sum(base,l);return `<div class="layer"><div><strong>${{unit:'Unit tests',integration:'Integration tests',e2e:'End-to-end tests'}[l]}</strong><p>${n.total?n.failed+' failed · '+n.skipped+' skipped':'No execution evidence yet'}</p></div><div><strong>${n.passed} passed</strong><p>${base?`${n.passed-b.passed>=0?'+':''}${n.passed-b.passed} vs baseline`:'Baseline not selected'}</p></div></div>`}).join('');
}
async function refresh(){try{const r=await fetch('/api/results',{cache:'no-store'});if(!r.ok)throw Error();data=await r.json();if(!manualCompare)comparison=data.baseline||'';
 const options=data.runs.map(r=>`<option value="${esc(r.id)}">${esc(r.id)}${r.id===data.baseline?' · BASELINE':''}</option>`).join('');
 $('#current').innerHTML='<option value="">Latest run (live)</option>'+options;$('#current').value=selected;
 $('#baseline').innerHTML='<option value="">No comparison</option>'+options;$('#baseline').value=comparison;render();
 }catch(e){$('#notice').textContent='Dashboard connection unavailable. Existing results may be stale.'}}
$('#current').addEventListener('change',e=>{selected=e.target.value;render()});$('#baseline').addEventListener('change',e=>{comparison=e.target.value;manualCompare=true;render()});
$('#services').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const run=data.runs.find(r=>r.id===selected)||data.runs[0];const s=run.services.find(s=>s.id===b.dataset.service);const x=s.layers[b.dataset.layer];$('#details').hidden=false;$('#detail-title').textContent=s.id+' / '+b.dataset.layer;
 $('#detail-content').innerHTML=`<p>${esc(labels[x.status])}${x.durationSeconds!=null?' · '+x.durationSeconds+' seconds':''}${x.exitCode!=null?' · exit '+x.exitCode:''}</p>${x.description?`<p>${esc(x.description)}</p>`:''}${x.error?`<p>${esc(x.error)}</p>`:''}${x.command?`<pre>${esc(x.command.join(' '))}</pre>`:''}${x.coverage?`<p>Coverage: ${percent(x.coverage,'line')} lines · ${percent(x.coverage,'branch')} branches</p>`:''}<div>${(x.artifacts||[]).map(a=>`<a target="_blank" rel="noopener" href="/evidence/${a.split('/').map(encodeURIComponent).join('/')}">${esc(a.split('/').pop())} ↗</a>`).join('')}</div>${(x.tests?.cases||[]).map(c=>`<div class="case"><span class="badge" data-status="${c.status}">${labels[c.status]}</span> ${esc(c.name)}${c.message?`<pre>${esc(c.message)}</pre>`:''}</div>`).join('')}`;$('#details').scrollIntoView({behavior:'smooth'})});
$('#close').onclick=()=>{$('#details').hidden=true};refresh();setInterval(refresh,5000);
